resources:
  - name: ric03uec_app
    type: gitRepo
    repoPath: ric03uec/app
    configuration:
      integrationName: ric03uec_github
      branches:
        only: master
    initialVersion:
      sha: master
      
pipelines:
  - name: build_infra
    steps:
      - name: bootstrap
        type: bash
        configuration:
          affinityGroup: build
          #nodePool: kermit_centos_pool
        setup:
          runtime:            
            type: image
            image:
              custom: 
                name: drydock/u16nodall
                tag:  v7.1.4
        requires:
          resources:
            - ric03uec_app
        execution:
          onExecute:
            - printenv
            - cd "$res_ric03uec_app_resourcePath"
            - switch_env nodejs 0.12
            - npm install
            - cd tests
            - ../node_modules/.bin/mocha --recursive "**/*.spec.js" -R mocha-junit-reporter --reporter-options mochaFile=../testresults.xml
            - ../node_modules/.bin/istanbul --include-all-sources cover -root "../routes" ../node_modules/mocha/bin/_mocha -- -R spec-xunit-file --recursive "**/*.spec.js"
            - ../node_modules/.bin/istanbul report cobertura --dir ../coverageReport
            - cd .. && ls
            - save_tests testresults.xml

      - name: test_func_next
        type: bash
        configuration:
          affinityGroup: build
        triggeredBy:
          steps:
            - bootstrap
        execution:
          onExecute:
            - printenv

      - name: parallel_1
        type: bash
        triggeredBy:
          steps:
            - test_func_next
        execution:
          onExecute:
            - printenv
            - echo $imageTag

      - name: parallel_2
        type: bash
        triggeredBy:
          steps:
            - test_func_next
        execution:
          onExecute:
            - printenv

      - name: parallel_3
        type: bash
        triggeredBy:
          steps:
            - test_func_next
        execution:
          onExecute:
            - printenv

      - name: final_step
        type: bash
        triggeredBy:
          steps:
            - parallel_2
            - parallel_1
            - parallel_3
        execution:
          onExecute:
            - printenv

  - name: run_ci
    steps:
      - name: first_step
        type: bash
        requires:
          resources:
            - ric03uec_app
        execution:
          onExecute:
            - printenv
